# module_2_features.py
import pandas as pd
import pandas_ta as ta
import numpy as np
import joblib
import os
from sklearn.preprocessing import StandardScaler


class FeatureEngineer:
    def __init__(self, window_size: int = 60):
        """
        Initializes the Synthesizer.
        :param window_size: How many historical candles the LSTM looks at per prediction.
        """
        self.window_size = window_size
        self.feature_columns = []
        self.scaler = StandardScaler()

    def save_scaler(self, filepath="models/scaler.pkl"):
        """Saves the fitted scaler for live trading standardization."""
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        joblib.dump(self.scaler, filepath)
        print(f"[ENGINEER] Scaler saved securely to {filepath}")

    def load_scaler(self, filepath="models/scaler.pkl"):
        """Loads a pre-trained scaler."""
        if os.path.exists(filepath):
            self.scaler = joblib.load(filepath)
            print(f"[ENGINEER] Pre-trained Scaler loaded from {filepath}")
        else:
            print(f"[WARNING] Scaler file {filepath} not found. Must train first!")

    def apply_technical_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Calculates stationary technical indicators."""
        print("[ENGINEER] Synthesizing Technical Indicators...")

        # 1. Momentum: RSI (Bounded 0-100)
        df['RSI_14'] = df.ta.rsi(length=14)

        # 2. Volatility: Normalized ATR (Percentage of Close Price)
        atr = df.ta.atr(length=14)
        df['ATR_pct'] = atr / df['close']

        # 3. Trend: Distance from 50 EMA (Percentage difference)
        ema_50 = df.ta.ema(length=50)
        df['EMA_50_dist'] = (df['close'] - ema_50) / ema_50

        # Drop NaN values generated by the lookback periods of indicators
        df.dropna(inplace=True)

        # Define our final feature set
        self.feature_columns = ['RSI_14', 'ATR_pct', 'EMA_50_dist']
        return df

    def engineer_target_variable(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates the Forward Log Return for the NEXT candle.
        This is the ground-truth value the LSTM will try to predict.
        """
        print("[ENGINEER] Calculating Forward Log Returns (Target)...")

        # Log Return Formula: ln(Price_t / Price_t-1)
        # We use shift(-1) to pull the NEXT candle's return up to the CURRENT row
        df['target_return'] = np.log(df['close'].shift(-1) / df['close'])

        # Drop the final row because it has no "next" candle to predict
        df.dropna(inplace=True)
        return df

    def normalize_data(self, df: pd.DataFrame, is_training: bool = True) -> pd.DataFrame:
        """Applies Z-Score standardization to the features."""
        print("[ENGINEER] Applying Z-Score Normalization...")

        if is_training:
            # If training, fit the scaler to the data and transform
            df[self.feature_columns] = self.scaler.fit_transform(df[self.feature_columns])
        else:
            # If live trading, ONLY transform based on the historical fit
            # (Prevents data leakage from the live market into the scaler)
            df[self.feature_columns] = self.scaler.transform(df[self.feature_columns])

        return df

    def create_3d_tensor(self, df: pd.DataFrame) -> tuple:
        """
        Transforms the 2D DataFrame into a 3D NumPy array for the LSTM.
        Returns X (Features Tensor) and y (Target Array).
        """
        print(f"[ENGINEER] Shaping 3D Tensor (Window Size: {self.window_size})...")

        # Extract raw numpy arrays for speed
        feature_data = df[self.feature_columns].values
        target_data = df['target_return'].values

        X, y = [], []

        # Slide the window across the dataset
        for i in range(self.window_size, len(df)):
            # Grab the block of historical data for the window
            window = feature_data[i - self.window_size: i]
            X.append(window)

            # Grab the target return for the candle immediately following the window
            y.append(target_data[i])

        X = np.array(X)
        y = np.array(y)

        print(f"[SUCCESS] Tensor X shape: {X.shape} | Target y shape: {y.shape}")
        return X, y